name: Bug Report
description: Template for bug reports
title: '[Bug]: '
assignees:
- asheroto
body:
- type: markdown
  attributes:
    value: |
      Please check to see if your feature already exists in the [Issues](https://github.com/asheroto/winget-install).

      Name your issue appropriately: give it a sentence that reads well enough for anyone seeing this in the release notes to know what it is.

      When writing out the issue details, please ensure you are writing it as if you were explaining it to somebody else, even if you will be working on and resolving the issue yourself. This helps others to understand the reasons for the issue and for it to be searchable in the future.
- type: checkboxes
  id: checklist
  attributes:
    label: Checklist
    description: Before continuing, make sure you have done the following.
    options:
    - label: I have verified no other issues exist related to my problem.
      required: true
    - label: |
        I have restarted my computer to confirm this is not a transitory problem.
      required: true
    - label: |
        I have verified that I am using the latest version of winget-install.
      required: true
    - label: |
        I have run the script with the `-DebugMode` argument and included the output below
      required: true
- type: textarea
  id: what-are-you-seeing
  attributes:
    label: What You Are Seeing?
    description: |
      In your own words, please describe the problem that you are
      experiencing. Please include screenshots if possible, as this can give a
      clearer indication of the problem.
  validations:
    required: true
- type: textarea
  id: what-is-expected
  attributes:
    label: What is Expected?
    description: |
      Instead of the behavior that you were seeing, what did you expect would
      be happening instead?
  validations:
    required: true
- type: textarea
  id: how-did-you-get-this-to-happen
  attributes:
    label: How Did You Get This To Happen?
    description: |
      Please include a complete set of reproducible steps that another user or
      maintainer of the repository can follow to get the same behavior that
      you are seeing.  NOTE: We may be unable to troubleshoot/respond to
      issues without reproducible steps. If you do not complete this section,
      there is a high chance your issue may be closed.
    value: |-
      1. I ran this
      2. I clicked on this
      3. But it only happens with this game
  validations:
    required: true
- type: textarea
  id: system-details
  attributes:
    label: System Details
    description: |
      Please include as many details about your system as possible. Sometimes,
      a problem may only happen on specific systems, and this information can
      be vital to resolving your issue. At minimum, please include your
      operating system and version. You can find this under `Settings > System > About`
    value: |-
      - Windows 10 Pro x64 20H2
  validations:
    required: true
- type: textarea
  id: additional-context
  attributes:
    label: Additional Context
    description: |
      Please include any other information here that you feel may be relevant
      to the problem you are seeing but is not covered in the previous
      sections.
    value: Screenshots, etc
- type: textarea
  id: output-with-debugmode
  attributes:
    label: Full Output With `-DebugMode`
    description: |
      Please run the script with the `-DebugMode` argument and include the output below.
